### PR TITLE
Do not hide invalid markdown emphasis

### PR DESCRIPTION
**Pull request by NALStudio**
|Before|After|
|-------|-----|
|Before|After|

Relevant links:
https://github.com/MyNihongo/MudBlazor.Markdown/pull/280#issuecomment-2487216477

### CODE REVIEW

**Comment by NALStudio** [comment]
Here is an example with all of the unsupported emphasis types:
workswithall

**Comment by MihailsKuzmins** [comment]
Thank you for addressing this issue, however, I would like to reuse `TryRenderMarkdownError` that we already have. I understand that your approach will render all valid markup inside unknown delimiters, but my approach will not.

So if you do not strongly disagree, I would like to propose the following implementation:

## MudMarkdown.razor.cs
```cs
case EmphasisInline x:
{
	if (!x.TryGetEmphasisElement(out var elementName))
	{
		var markdownValue = x.Span.TryGetText(Value);
		TryRenderMarkdownError(markdownValue, builder, MarkdownErrorElement.Span);
		continue;
	}

	builder.OpenElement(ElementIndex++, elementName);
	RenderInlines(x, builder);
	builder.CloseElement();
	break;
}

// some code omitted

case PipeTableDelimiterInline x:
{
	// It usually indicates that there are some issues with table markdown
	var markdownValue = x.Parent?.ParentBlock?.Span.TryGetText(Value);
	TryRenderMarkdownError(markdownValue, builder, MarkdownErrorElement.Div); // <-- only this changes

	break;
}

// some code omitted

protected virtual void TryRenderMarkdownError(string? text, RenderTreeBuilder builder, string elementName) // <-- a new parameter is added
{
	if (string.IsNullOrEmpty(text))
		return;

	builder.OpenElement(ElementIndex++, elementName); // <-- only this changes
	builder.AddAttribute(ElementIndex++, "class", "markdown-error");
	builder.AddContent(ElementIndex++, text);
	builder.CloseElement();
}
```

## Enums/MarkdownErrorElement.cs (new)
```cs
namespace MudBlazor;

internal static class MarkdownErrorElement
{
	public const string Div = "div", Span = "span";
}

```

| Markdown | Browser |
| - | - |
| image | image |

**Comment by NALStudio** [comment]
I've implemented the feature as you requested! :)
<br/> 

_A couple of things to note:_

I decided to omit the `MarkdownErrorElement` class/enum entirely as it seemed quite pointless to have an enum just for a couple of HTML elements. I just pass in the element as a string instead.

I noticed that there are css classes and namespaces that are not named as mudblazor markdown. It would be cleaner if they are changed accordingly `markdown-error` => `mud-markdown-error` and `namespace MudBlazor;` => `namespace MudBlazor.Markdown;`. <br />This does break backwards compatibility though, so I'll leave this up to you to decide if it's worth implementing as it's out of the scope of this PR anyways.

**Comment by MihailsKuzmins** [comment]
Thanks.

> I decided to omit the MarkdownErrorElement class/enum entirely as it seemed quite pointless to have an enum just for a couple of HTML elements. I just pass in the element as a string instead.

I just wanted to extract it, so that if it is necessary to pass `"span"` again in some other place it will enough to pass a constant value instead of a "magic string", but probably it is all right for now.

> I noticed that there are css classes and namespaces that are not named as mudblazor markdown. It would be cleaner if they are changed accordingly markdown-error => mud-markdown-error and namespace MudBlazor; => namespace MudBlazor.Markdown;.
This does break backwards compatibility though, so I'll leave this up to you to decide if it's worth implementing as it's out of the scope of this PR anyways.

As for the namespace, it's better to have the same namespace as the main library does. As for CSS classes, I guess adding the `mud` prefix should not hurt. But as you said, it is out of the scope of this issue.

**Review by MihailsKuzmins — APPROVED** [review]

**Pull request merged**
